blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://docs.yasumu.dev
    about: Check the documentation for answers to common questions
  - name: Discussions
    url: https://github.com/yasumu-app/yasumu/discussions
    about: Ask questions and discuss ideas with the community

